#!/bin/bash
rm -rf *.class
cd chess
rm -rf *.class
cd pieces
rm -rf *.class
cd ../..

javac ChessGame.java
echo " " 
echo "Program is running..."
echo " "
java  ChessGame Tue_Oct_17_06:47:59_MSK_2017.save

rm -rf *.class
cd chess
rm -rf *.class
cd pieces
rm -rf *.class
cd ../.. 
