#!/bin/bash
rm -rf *.class
cd chess
rm -rf *.class
cd pieces
rm -rf *.class
cd ../..

javac ChessGame.java
echo " " 
echo "Program is running..."
echo " "
java  ChessGame 

rm -rf *.class
cd chess
rm -rf *.class
cd pieces
rm -rf *.class
cd ../.. 
